version: "3"

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
    
networks:
  loki:
    driver: bridge
  prom_network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prom_network

  blackbox:
    image: prom/blackbox-exporter:v0.16.0
    container_name: blackbox
    restart: always
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    networks:
      - prom_network
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    ports:
      - "9115:9115"
         
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: 
      - -config.file=/etc/loki/loki-config.yml
      - -print-config-stderr=true
    networks:
      - loki
        
  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - "./promtail-config.yml:/etc/promtail/promtail-config.yml"
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - loki
    ports:
      - "9080:9080"

  postgres-exporter-pgserver94:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres@172.18.0.1:5432/postgres?sslmode=disable # change
    ports:
      - "9187:9187"

  # older PostgreSQL 9.2
  #postgres-exporter-pgserver92:
  #  image: wrouesnel/postgres_exporter:latest
  #  configs:
  #    - source: postgres92_exporter_config
  #      target: /etc/postgres_exporter/queries.yaml
  #  deploy:
  #    mode: replicated
  #    replicas: 1
  #  environment:
  #    - DATA_SOURCE_NAME=postgresql://postgres@pgserver92.example.com:5432/postgres?sslmode=disable
  #    - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/queries.yaml
  #    - PG_EXPORTER_DISABLE_DEFAULT_METRICS=true

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    depends_on:
      - prometheus
      - loki
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    links:
      - influxdb
    ports:
      - "3000:3000"